warriorsproject/models.py
from warriorsproject import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
# need to set up db inside of the __init__.py under warriorsproject folder

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

# for logins
class User(db.Model, UserMixin):
    
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    
    def __init__(self, email, username, password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)
        
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)    
        

class Runners(db.Model):
    # manual table name choice
    __tablename__ = 'runners'
    
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.Text)
    lastname = db.Column(db.Text)
    age = db.Column(db.Integer)
    group = db.Column(db.Text)
    runs = db.relationship('Run', backref='runner', lazy='dynamic') # one to many
    coach_id = db.Column(db.Integer, db.ForeignKey('coaches.id'))
    
    
    def __init__(self, firstname, lastname, age, group):
        self.firstname = firstname
        self.lastname = lastname
        self.age = age
        self.group = group
        
    def __repr__(self):
        if self.coach:
            return f"Runner's name is {self.firstname} {self.lastname} and coach is {self.coach.firstname}"
        else:
            return f"Runner's name is {self.firstname} {self.lastname} and has no coach yet!" 
        
    def report_runs(self):
       print("Here are my runs:")
       for run in self.runs:
           print(run.item_name)     
            
    
class Run(db.Model):
    
    __tablename__ = 'runs'
    
    id = db.Column(db.Integer, primary_key=True)
    item_name = db.Column(db.Text)
    miles = db.Column(db.Float)
    timehours = db.Column(db.Integer)
    timemin = db.Column(db.Integer)
    timesec = db.Column(db.Integer)
    runner_id = db.Column(db.Integer, db.ForeignKey('runners.id'))
    
    def __init__(self, item_name, runner_id):
        self.item_name = item_name
        self.runner_id = runner_id
        
    

class Coach(db.Model):
    __tablename__ = 'coaches'
    
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.Text)
    lastname = db.Column(db.Text)
    runners = db.relationship('Runners', backref='coaches', lazy='dynamic') # one to many
      
    
    def __init__(self, firstname, lastname):
        self.firstname = firstname
        self.lastname = lastname

warriorsproject/coaches/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, BooleanField, DateTimeField,
                     RadioField, SelectField, TextField, 
                     TextAreaField, SubmitField, IntegerField)
from wtforms.validators import DataRequired, InputRequired

class AddForm(FlaskForm):
    
    firstname = StringField('First Name: ')
    lastname = StringField('Last Name: ')
    submit = SubmitField('Add Coach') 

warriorsproject/runners/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, BooleanField, DateTimeField,
                     RadioField, SelectField, TextField, 
                     TextAreaField, SubmitField, IntegerField)
from wtforms.validators import DataRequired, InputRequired

class AddForm(FlaskForm):
    
    firstname = StringField('First Name: ')
    lastname = StringField('Last Name: ')
    age = IntegerField('Age: ')
    group = StringField('Trainng Group: ')
    submit = SubmitField('Add Runner')
    
class DelForm(FlaskForm):
    
    id = IntegerField('ID Number of Runner: ') 
    submit = SubmitField('Remove Runner')

warriorsproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail
from werkzeug.utils import secure_filename

login_manager = LoginManager()

app = Flask(__name__)

app.config['MAIL_SERVER'] = "smtp.gmail.com"
app.config['MAIL_PORT'] = 587
app.config['MAIL_USE_TLS'] = True
app.config['MAIL_DEFAULT_SENDER'] = "wareliteracing@gmail.com"
app.config['MAIL_USERNAME'] = "wareliteracing@gmail.com"
app.config['MAIL_PASSWORD'] = "Zapata99!"
mail = Mail(app)

basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SECRET_KEY'] = "mysecretkey"
app.config['TESTING'] = False
app.config['LOGIN_DISABLED'] = False
app.config['UPLOAD_FOLDER'] = basedir + '/upload'
### SQL DB Section #####

app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'app.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

Migrate(app,db) # so you can make changes to actual db
# steps to migrate are - flask db migrate -m "something" then flask db upgrade

### login section
login_manager.init_app(app)
login_manager.login_view = 'login'

from warriorsproject.runners.views import runners_blueprint
from warriorsproject.coaches.views import coaches_blueprint

app.register_blueprint(coaches_blueprint, url_prefix='/coaches')
app.register_blueprint(runners_blueprint, url_prefix='/runners')
 

warriorsproject/coaches/views.py
from flask import Blueprint, render_template, redirect, url_for
from warriorsproject import db 
from warriorsproject.models import Coach
from warriorsproject.coaches.forms import AddForm

coaches_blueprint = Blueprint('coaches', __name__, template_folder='templates/coaches')


@coaches_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    
    form = AddForm()
    
    if form.validate_on_submit():
        firstname = form.firstname.data
        lastname = form.lastname.data
        new_coach = Coach(firstname, lastname)
        db.session.add(new_coach)
        db.session.commit()
        
        return redirect(url_for('coaches.list'))
        
    return render_template('add_coach.html', form=form) 


@coaches_blueprint.route('/list')
def list():
    
    coaches = Coach.query.all()
    return render_template('list_coaches.html', coaches=coaches)

warriorsproject/runners/views.py
from flask import Blueprint, render_template, redirect, url_for
from warriorsproject import db 
from warriorsproject.models import Runners
from warriorsproject.runners.forms import AddForm, DelForm

runners_blueprint = Blueprint('runners', __name__, template_folder='templates/runners')


@runners_blueprint.route('/add', methods=['GET', 'POST'])
def add():
    
    form = AddForm()
    
    if form.validate_on_submit():
        firstname = form.firstname.data
        lastname = form.lastname.data
        age = form.age.data
        group = form.group.data 
        new_runner = Runners(firstname, lastname, age, group)
        db.session.add(new_runner)
        db.session.commit()
        
        return redirect(url_for('runners.list'))
        
    return render_template('add_runner.html', form=form)   


@runners_blueprint.route('/list')
def list():
    
    runners = Runners.query.all()
    return render_template('list_runners.html', runners=runners)


@runners_blueprint.route('/delete', methods=['GET', 'POST'])
def delete():
    
    form = DelForm()
    
    if form.validate_on_submit():
        
        id = form.id.data
        runner = Runners.query.get(id)
        db.session.delete(runner)
        db.session.commit()
        
        return redirect(url_for('runners.list'))
    return render_template('delete_runner.html', form=form)

warriorsproject/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Whittier Warriors Youth Running</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon"type="image/ico" href="../static/img/warfavicon.ico">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
        <link rel="stylesheet" href="../static/css/style.css">
        <link href="https://fonts.googleapis.com/css2?family=Original+Surfer&display=swap" rel="stylesheet">
        <script
  src="http://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>
    <body>
        <!-- Navigation bar starts here-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{{ url_for('index') }}">Home <span class="sr-only">(current)</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('virtual_coach') }}">Virtual Coach </a>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Youth Running Program
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{{ url_for('warriors') }}">Youth Program Info</a>
                    <a class="dropdown-item" href="{{ url_for('successstories') }}">Success Stories</a>
                    <a class="dropdown-item" href="{{ url_for('teampics') }}">Team Pics</a>
                    <a class="dropdown-item" href="{{ url_for('schedule') }}">Track 2020 Schdule</a>
                                        
                  </div>
                </li>  
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Running Tools
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{{ url_for('pacechart') }}">Pace Chart</a>
                    <a class="dropdown-item" href="{{ url_for('trainingpacecal') }}">Pace Calculator</a>
                    <a class="dropdown-item" href="{{ url_for('trainingpacecal') }}">Something else here</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Warrior Running Log
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{{ url_for('runners.list') }}">Runner Database View</a>
                    <a class="dropdown-item" href="{{ url_for('runners.add') }}">Add Runner</a>
                    <a class="dropdown-item" href="{{ url_for('coaches.add') }}">Add Coach</a>
                    <a class="dropdown-item" href="{{ url_for('runners.delete') }}">Delete Runner</a>
                    
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Training
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{{ url_for('workouts') }}">Workouts</a>
                    
                    
                  </div>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('contactus') }}">Contact Us</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('logout') }}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('login') }}">Log In</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('register') }}">Register</a>
                </li>
                {% endif %}
              </ul>
            </div>
          </nav>
          <br>
        <div style="background-image:linear-gradient(black,black), url({{ url_for('static', filename='img/tracksunset.jpg') }})" class="homepagebg">
          <div>
        <img class="img-fluid logo-medium mx-auto d-block" src="../static/img/warriorlogo_med.png" alt="warriors logo">
          </div>
        </div>
          {% block content %}


          {% endblock %}

warriorsproject/templates/contactus.html
{% extends 'base.html' %}


{% block content %}
    <br>
    <!-- Contact us page starts here-->
    <h1 class="center">We are waiting to hear from you!</h1>
    <br>
    <div style="background-image: url({{ url_for('static', filename='img/tracksunset.jpg') }})" class="container homepagebg">
    <!-- contact us form starts here-->
    <div class="container">
        <form action="{{url_for('contactus')}}" method="post" enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ form.hidden_tag() }}
        <br>
        <div class="row text-light">
        <div class="col">
            {{ form.first.label }} {{ form.first }}
        </div>
        <div class="col">
            {{ form.last.label }} {{ form.last }}
        </div>
        </div>
        <br>
        <div class="row text-light">
        <div class="col">
            {{ form.email.label }} {{ form.email }} 
        </div>
        <div class="col">
            {{ form.phonenum.label }} {{ form.phonenum }}
        </div>
        </div>
        <br>
        <div class="row text-light">
        <div class="col">
            {{ form.message.label }}
            <br>
            {{ form.message(cols='65',rows='5') }} 
        </div>
        <div class="col">
            {{ form.file.label }} {{ form.file }}
        </div>
        </div>
        <br>
        {{ form.submit() }}
        <br>
    </form>
    </div>
    
    
    
{% endblock content %}

warriorsproject/templates/hillrepeats.html
{% extends 'base.html' %}


{% block content %}

        <br>
        <div class="container">
            <div class="container center">
                <img src="/static/img/marathonfeet.jpg" class="img-fluid w-50" alt="marathon pace">
            </div>
            <h1 class="center">Hill Repeats</h1>
            <br>
            <p>Every Wednesday we will highlight some training technique or a particular workout including visiting some local teams or clubs to talk to them about what they do. Today I want to focus on what I consider one of the most under appreciated and overlooked workouts in a distance runners arsenal, Hill Repeats. If done correctly they can make you stronger, faster, more explosive, and even improve your overall running form! Hill repeats can be done many different ways but all fall into 2 variations. Short Hills and Long Hills.

                Short hill repeats consist of finding a hill 4% to 7% grade about 100 to 150 meters in length. I know its very hard to know what 4% to 7% looks like so it should be steeper than the long hills we will discuss in a bit but not so steep you have a hard time walking up it not to mention running fast up them. These are relatively short and the effort last about 15 to 30 seconds so they are run almost all out. Lets say around 90% to 95% of an all out sprint. You are going anaerobic (lack of oxygen) meaning you should reach the top very much out of breathe. Run these but building up the first 10-20 meters then working to full speed. Focus on good uphill running form. Short, quick, powerful strides with arms a bit higher then  normal and head in neutral position meaning facing straight forward. Eyes are key on these keep your eyes focused on the top of this hill not looking at the ground. This will keep your form intact and keep your mind focused on the correct effort. Near the top of the hill make sure you do not slow down but if anything pick up the pace at what we call the "crest" of the hill as it flattens out run through the top as it flattens out. This will prepare you for great racing strategy to blast past your opponents not on the hill itself but on the crest and right after. More on this in some racing strategy blog entries.
                
                ​Long hill repeats are similar to short hills but of course longer =-) I like to make these 400 meters but you can go with anything 300 to 500 meters. Much longer and you will lose the ability to run them correctly. Much shorter you will not gain the additional benefits of the long vs short hill repeats. Run these very similar to the short hills except your effort needs to be slightly lower about 85% to 90% with the first half a little slower and a pickup at the mid way point. Very much drive the last section and run over the crest with aggressiveness. While the short hills will give you true power and explosiveness overall not just for a finishing kick the long hills will give you power and speed endurance again not just in longer hilly courses but even on flat races. There is a mental factor to long hills that is often over looked. Push up a 1/4 of a mile hill faster than you will during a race will make kicking on a flat 400 meters seem easy or running any hill seem like just another day at the office! As far as number of reps that will vary but for short hills 12 to 20 while on the long hills 6 to 10 will do it for a great workout! Recovery for both is a slow jog back down the hill regroup for 10 sec once down and go again! Don't forget at least a 2 mile warm-up run at easy pace and 2 miles cool-down easy as well. Give this workout a try and provide feedback or ask question anytime! As always go chase those running dreams and enjoy!</p>
        
        </div>

    
{% endblock content %}

warriorsproject/templates/home.html
{% extends 'base.html' %}


{% block content %}

        
        <div class="container">
        <h1 class="center text-dark">Welcome to the NEW Warriors Youth Running Website!</h1>
        <h1 class="center text-dark">Coming Soon!</h1>
        {% if current_user.is_authenticated %}
        <h3 class="center text-light">Welcome back {{ current_user.username }}!</h3>
        {% else %}
        <h3 class="center text-dark">Please login or register if you are a member of our Team</h3>
        <h3 class="center text-dark">If you are part of the general public please enjoy all our public running resources!</h3>
        {% endif %}
        </div>

    
{% endblock content %}

warriorsproject/templates/paceplan1600.html
{% extends 'base.html' %}


{% block content %}

    <br>
    <div class="container">
    <h1>Warriors Virtual Coach says:</h1>
    
    {% if session['strategy'] == 'even_pace' %}
    <h2>{{ session['first'] }} {{ session['last']}} since you are planning to run an "Even Pace" and are aiming to run 
        a time of {{ session['target_min']}}:{{ session['target_sec'] }} here are the paces per lap I recommend: </h2>
    <ul> 
        <li>lap1: {{ session['perlapmin'] }}:{{ session['perlapsec'] }}</li>
        <li>lap2: {{ session['perlapmin'] }}:{{ session['perlapsec'] }} </li>
        <li>lap3: {{ session['perlapmin'] }}:{{ session['perlapsec'] }} </li>
        <li>lap4: {{ session['perlapmin'] }}:{{ session['perlapsec'] }} </li>
    </ul>

    {% elif session['strategy'] == 'front_runner' %}
    <h2>{{ session['first'] }} {{ session['last']}} since you are planning to run as a "Front Runner" and are aiming to run 
        a time of {{ session['target_min']}}:{{ session['target_sec'] }}, here are the paces per lap I recommend: </h2>
    <ul> 
        <li>lap1: {{ session['fr_lap1min'] }}:{{ session['fr_lap1sec'] }}</li>
        <li>lap2: {{ session['fr_lap2min'] }}:{{ session['fr_lap2sec'] }} </li>
        <li>lap3: {{ session['fr_lap3min'] }}:{{ session['fr_lap3sec'] }} </li>
        <li>lap4: {{ session['fr_lap4min'] }}:{{ session['fr_lap4sec'] }} </li>
    </ul>

    {% elif session['strategy'] == 'off_pace' %}
    <h2>{{ session['first'] }} {{ session['last']}} since you are planning to run "Off the Pace" and are aiming to run 
        a time of {{ session['target_min']}}:{{ session['target_sec'] }}, here are the paces per lap I recommend: </h2>
    <ul> 
        <li>lap1: {{ session['op_lap1min'] }}:{{ session['op_lap1sec'] }}</li>
        <li>lap2: {{ session['op_lap2min'] }}:{{ session['op_lap2sec'] }} </li>
        <li>lap3: {{ session['op_lap3min'] }}:{{ session['op_lap3sec'] }} </li>
        <li>lap4: {{ session['op_lap4min'] }}:{{ session['op_lap4sec'] }} </li>
    </ul>
    {% endif %}
    </div>

        
    
{% endblock content %}

warriorsproject/templates/register.html
{% extends 'base.html' %}


{% block content %}

        <br>
        <h1 class="center">Welcome to the NEW Warriors Youth Running Website!</h1>
        <h1 class="center">Coming Soon!</h1>
        <br>
        <form method='POST'>
                {{ form.csrf_token }}
                {{ form.hidden_tag() }}
                {{ form.email.label }}{{ form.email() }}
                {{ form.username.label }}{{ form.username() }}
                {{ form.password.label }}{{ form.password() }}
                {{ form.pass_confirm.label }}{{ form.pass_confirm() }}
                {{ form.submit() }}       
        </form>
        

    
{% endblock content %}

warriorsproject/templates/teampics.html
{% extends 'base.html' %}


{% block content %}
<br>
<div class="container w-50">
    <div id="carouselExampleControls" class="carousel slide " data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="/static/img/boys.jpg" class="w-50" alt="boys runners"><h4>hello</h4>
        </div>
        <div class="carousel-item">
          <img src="/static/img/girls.jpg" class="w-50" alt="girls runners">
        </div>
        <div class="carousel-item">
          <img src="/static/img/natsqual.jpg" class="w-50" alt="national championship qualifiers">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next w-50" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
    
{% endblock content %}

warriorsproject/templates/threshold.html
{% extends 'base.html' %}


{% block content %}

        <br>
        <div class="container">
            <div class="container center">
                <img src="/static/img/tempo1.jpg" class="img-fluid w-50" alt="tempo areobic threshold">
            </div>
            <h1 class="center">Areobic Threshold</h1>
            <br>
            Aerobic Threshold (AT) workouts or Tempo as they are commonly referred to are in my opinion one of the biggest weapon a coach has to train any level of distance runners from Marathoners to even 800 meter runs this workout is critical. Now don't let the debate on whether Tempo and Aerobic Threshold runs are the same or slightly different we can get into that later in future articles for now lets focus on how to run a true Aerobic Threshold (AT) workout why its so helpful to fully develop a distance runner. 

Aerobic Threshold workouts can be done in many variations from ones broken into pieces to the more traditional ones but for the sake of today's article we will focus on the traditional AT runs. Keep in mind these are not to be used with runners that have just started to run regardless of age. You need at least a solid 2-3 months of consistent training before these should be introduced an even then should be done gradually. As an introduction to this workout or any other form of speed workouts its a good idea to through in workouts such as fartleks a few weeks before. These will get the runners comfortable with more aggressive pacing but in short burst that are achievable and encouraging. We will cover fartleks in the future as well for those that are not familiar with them. 

So why should we do AT runs as part of our training cycle? We are already doing Vo2Max and hill repeats and interval speed training so why do we need this workout as part of our arsenal? These workouts focus on a particular system that is critical to any distance runner. There is a point in your pace where once you speed up to that pace you start to significantly buildup lactate which will cause a runner to slow down. The key of this workout is to push that threshold or imaginary line more and more so that as a runner you can run farther at a faster pace before that buildup causes the slowing. Lactate is a simple a by-product of metabolism that is natural and part of a healthy individual body's reaction but too much of it will slow a runner so we do these AT workouts to increase that point where lactate starts to overwhelm the muscles.

Now to put this knowledge to use in training. As any speed workouts this should be done with a 1-2 mile warm-up at Easy pace to start. The AT run should be done in an area where you can safely run without crossing streets or other area where you would need to stop and disrupt the workout. A trail or a large street loop where you don't have to cross a street by turning right each time at each corner to make a square loop. You may need to do the loop multiple times to reach the planned distance or time. You can even do this on a track but I will warn you its mentally tougher to do that but that in itself is anther topic for a future discussion. The AT run typical should be 20 to 30 min so depending you your ability it will be anywhere from 3 to 6 miles. For those training for 8K and below there is no need to go much longer but those training 10K or especially Half and Full Marathon should build up to doing 8-12 miles of AT workouts. Here is the critical part. Make sure you are doing this at the right pace. Too fast and you will not improve you threshold as you will be going anaerobic and too slow you will not get the benefit to push that threshold up. Use our WAR Training pace calculator to find your correct pace based on your most recent 5K or other similar race distance. Once you calculate based on that time look at the "tempo pace: and use this. If you don't have a good race to use to calculate this pace use this rule of thumb. The run should feel "control hard" meaning you can hold that pace for a while but its difficult. Or do the talk test. If you are asked a question you could answer yes or no but not hold any long conversation at that pace

Now to put this all together and place it correctly in your training cycle. Do an AT workout about every 2 to 3 weeks. Now this varies depending on many factors but its a good rule of thumb. I've used them weekly training for a marathon and every 3 weeks training runners for a 3200 meter race. If at all possible don't but this workout back to back with other hard days and definitely not too close to an upcoming race. It takes a good 3-5 days to recovery from this workout and longer than most other speed workouts. As always do these with a warm-up and with a proper cool-down 1-2 miles for each. Make sure pace is even on these runs and no kicking at the end to make up time it takes you anaerobic and our of the systems zone we are trying to improve. Here is what this workout might look like:
        
        </div>

    
{% endblock content %}

warriorsproject/templates/welcome_user.html
{% extends 'base.html' %}


{% block content %}

        <br>
        <div class="jumbotron container">
        <h1 class="center">Congrats you are logged in!</h1>
        <h1 class="center">Enjoy Running through our Site!</h1>
        </div>
{% endblock content %}